---
title: "`r params$title`"
output: html_document
params:
  dataset: NULL
  metadata_file: NULL
  title: NULL
---

```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(knitr)
meta_summary <- readxl::read_excel(params$metadata_file, sheet = 3,range = "A1:B10")
meta_details <-readxl::read_excel(params$metadata_file, sheet = 4,range = "A1:B6")
meta_columns <- readxl::read_excel(params$metadata_file, sheet = 5)

meta_factors_list <- read_named_tables(params$metadata_file)
df <- params$dataset

```

## Sections {.tabset}

### Core Dataset info
```{r core_dataset, echo = FALSE}
meta_summary[] <- lapply(meta_summary, function(col) {
  if (is.character(col)) gsub("[\r\n]", " ", col) else col
})
knitr::kable(meta_summary,na="")
```

### Dataset details
```{r details_dataset, echo = FALSE}
meta_details[] <- lapply(meta_details, function(col) {
  if (is.character(col)) gsub("[\r\n]", " ", col) else col
})
knitr::kable(meta_details,na="")
```

### Dataset columns
```{r columns_dataset, echo = FALSE}
meta_columns <- meta_columns[!apply(meta_columns, 1, function(x) all(is.na(x))), ]
meta_columns[is.na(meta_columns)] <- ""
knitr::kable(meta_columns,na="")
```

### Factor values {.tabset}
```{r factor_tables, results = 'asis',echo=FALSE}
for (name in names(meta_factors_list)) {
  cat("####", name, "\n\n")
  column_desc <- meta_columns$variable_name[meta_columns$variable_code==name]
  cat(paste0("**",column_desc,"**"), "\n")
  df_temp <- meta_factors_list[[name]]
  print(knitr::kable(df_temp[order(tolower(as.character(df_temp$code))),]))
}
```

### Key statistical info {.tabset}

#### Boxplots {.tabset}
```{r boxplots,results = 'asis',echo=FALSE}

numeric_columns <- names(df)[sapply(df, is.numeric)]
for (name in numeric_columns){
  cat("#####", name, "\n\n")
  bp <- ggplot2::ggplot(df, ggplot2::aes_string(x = name)) + 
    ggplot2::geom_boxplot(fill = "skyblue", color = "black") + 
    ggplot2::labs(title = paste("Boxplot of", name), x = name, y = "Value") + 
    ggplot2::theme_minimal()
 
  print(bp)

  cat("\n\n")
}
```


#### Histograms {.tabset}
```{r histograms,results = 'asis',echo=FALSE}
for (name in numeric_columns){
  cat("#####", name, "\n\n")
  hp <- ggplot2::ggplot(df, ggplot2::aes_string(x = name)) + 
    ggplot2::geom_histogram(binwidth = 1, fill = "skyblue", color = "black") + 
    ggplot2::labs(title = paste("Histogram of", name), x = name, y = "Frequency") + 
    ggplot2::theme_minimal()
 
  print(hp)

  cat("\n\n")
}
```

### Completion Rate {.tabset}

#### Overall missingness
```{r missingness, echo=FALSE}
 # Createt a dataset which looks at completeness per field
  completeness_df <- data.frame(
    Variable = names(df),
    Complete_Count = sapply(df, function(x) sum(!is.na(x))),
    Total_Count = nrow(df),
    Complete_Percent = round(sapply(df, function(x) mean(!is.na(x))) * 100, 2),
    stringsAsFactors = FALSE
  )

  # Create the plot
  completeness_plot <- ggplot2::ggplot(data = completeness_df, ggplot2::aes(x = Variable, y = Complete_Percent)) +
    ggplot2::geom_bar(stat = "identity", fill = "steelblue") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = "Complete Data Percentage by Variable",
      x = "Variable",
      y = "Complete Percentage (%)"
    ) +
    ggplot2::theme_minimal()
  
  plotly::ggplotly(completeness_plot)

```

```{r heatmaps,results = 'asis',echo=FALSE}

factor_columns <- names(df)[sapply(df, is.factor)]

for (name in factor_columns){
  cat("####", name, "\n\n")
  hm <- plot_completeness_heatmap(df,name)

  print(hm)

  cat("\n\n")
}
```

